select 1 from member where id='oneNone';
select ID, PWD, NAME, EMAIL, ZIP_NUM, ADDRESS, PHONE, LEAVE_YN, JOIN_DATE 
  from member where id='oneNone';
INSERT INTO MEMBER(ID, PWD, NAME, EMAIL, ZIP_NUM, ADDRESS, PHONE)
VALUES('three', '1111', '세번째', 'three@test.co.kr', '133-110', '서울시 성동구 성수동 1가 1번지 21호', '010-333-3333');
DELETE FROM MEMBER WHERE ID = 'three'; 
SELECT ID, PWD, NAME, EMAIL, ZIP_NUM, ADDRESS, PHONE, LEAVE_YN, JOIN_DATE FROM MEMBER WHERE NAME LIKE '%째%'; 

SELECT ID,PWD,NAME,EMAIL,ZIP_NUM,ADDRESS,PHONE,LEAVE_YN,JOIN_DATE FROM MEMBER;
SELECT count(*) FROM address;

select ZIP_NUM, SIDO, GUGUN, DONG, ZIP_CODE, BUNJI from address where dong like '%구암동%';

-- cart
SELECT NO,PNO,MEMBERID,QUANTITY,RESULT,REG_DATE FROM CART;
SELECT NO,PNO,MEMBERID,QUANTITY,RESULT,REG_DATE FROM CART WHERE NO='2';

insert into cart(memberid, pno, quantity) values('two', 1, 1);
DELETE FROM CART WHERE NO = '41'; 


select * from cart_view where id='one' order by cseq DESC;
SELECT NO, MEMBERID, PNO, MNAME, PNAME, QUANTITY, REG_DATE, SALEPRICE, RESULT
        FROM CART_VIEW;
SELECT c.NO , c.MEMBERID , c.PNO , m.NAME , p.NAME, c.QUANTITY, c.REG_DATE, p.MARGIN , c.RESULT 
  FROM cart c JOIN MEMBER m ON c.MEMBERID = m.ID JOIN PRODUCT p ON c.PNO =p.NO 
 WHERE result = '1';

-- PRODUCT
SELECT * FROM BEST_PRO_VIEW;
SELECT * FROM NEW_PRO_VIEW;


-- ORDER
SELECT *
  FROM USER_SEQUENCES;

SELECT DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NUM,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT FROM ORDER_VIEW;
SELECT DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NUM,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT FROM ORDER_VIEW ORDER BY DNO;

SELECT DNO,ONO,MID,ORDER_DATE,PNO,QUANTITY,MNAME,ZIP_NUM,ADDRESS,PHONE,PNAME,SALEPRICE,RESULT 
  FROM ORDER_VIEW
 WHERE MID = 'two' AND RESULT LIKE '1' AND ONO = '3';
SELECT ORDER_DETAIL_NO_SEQ.CURRVAL FROM dual;

SELECT MAX(NO) FROM ORDERS;
SELECT DISTINCT ONO 
        FROM ORDER_VIEW
        WHERE MID='one' AND RESULT LIKE '1'  
        ORDER BY ONO DESC;

SELECT DNO, ONO, MID, ORDER_DATE, PNO, QUANTITY, MNAME, ZIP_NUM, ADDRESS, PHONE, PNAME, SALEPRICE, RESULT
		FROM ORDER_VIEW
		WHERE MNAME like '김나%'
		ORDER BY RESULT, ONO DESC;
       
UPDATE ORDER_DETAIL
   SET RESULT_YN='1'
 WHERE ONO = 1;	
	
SELECT * FROM ORDER_DETAIL;

-- 
SELECT * FROM cart;
SELECT * FROM product;
SELECT * FROM member;
--

SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;
SELECT * FROM ORDER_VIEW;
SELECT * FROM CART;
SELECT DNO, ONO, MID, ORDER_DATE, PNO, QUANTITY, MNAME, ZIP_NUM, ADDRESS, PHONE, PNAME, SALEPRICE, RESULT
  FROM ORDER_VIEW WHERE MID = 'two' AND ono=(SELECT max(no) FROM ORDERS) AND RESULT = '1';
  
SELECT max(no) FROM ORDERS;
-- ORDER
insert into orders(id) values('two'); -- ono4

insert into order_detail(ono, pno, quantity) values((SELECT max(no) FROM ORDERS), 9, 3);
insert into order_detail(ono, pno, quantity) values((SELECT max(no) FROM ORDERS), 10, 3);
insert into order_detail(ono, pno, quantity) values((SELECT max(no) FROM ORDERS), 11, 3);

SELECT * FROM ORDER_VIEW where mid='two' and result='1' order by ono DESC;

select distinct ono from order_view 
where mid='two' and result='1' order by ono DESC;

SELECT ONO, MID, MNAME, PHONE, ZIP_NUM, ADDRESS, DNO, ORDER_DATE, RESULT,
       PNO, PNAME, QUANTITY, SALEPRICE 
  FROM ORDER_VIEW 
 WHERE MID='two' AND RESULT LIKE '%' ;
 

--QnA
SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITE_DATE FROM QNA;
update qna SET rep='답변내용', rep_yn='2';

SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITE_DATE FROM QNA WHERE ID='one' ORDER BY NO DESC;
SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITE_DATE FROM QNA WHERE NO=2;
INSERT INTO QNA (SUBJECT, CONTENT, ID) VALUES(?, ?, ?);

-- worker
SELECT * FROM worker;

SELECT 1 FROM worker WHERE id='admin' AND pwd='admin';
SELECT 1 FROM worker WHERE id='admin' AND pwd='1111';
SELECT 1 FROM worker WHERE id='aaaa' AND pwd='admin';
 
-- admin product
select * from product;
select count(*) from product;
select count(*) from product where name like '%%%';

SELECT NO, REG_DATE, NAME, PRICE, SALEPRICE , DEL_YN, BEST_YN 
  FROM PRODUCT 
 WHERE NAME LIKE '%%' ORDER BY NO DESC;

SELECT NO, REG_DATE, NAME, PRICE, SALEPRICE , DEL_YN, BEST_YN 
  FROM PRODUCT 
 WHERE NAME LIKE '%슬%' ORDER BY NO DESC;
 
INSERT INTO PRODUCT(NAME, KIND, PRICE, SALEPRICE, MARGIN, CONTENT, IMAGE) VALUES(?,?,?,?,?,?,?);
UPDATE PRODUCT SET KIND=?, DEL_YN=?, NAME=?, PRICE=?, SALEPRICE=?, MARGIN =?, CONTENT=?, IMAGE=?, BEST_YN=? WHERE NO=?

-- 주문관리
select * from order_view;

SELECT DNO, ONO, MID, ORDER_DATE, PNO, QUANTITY, MNAME, ZIP_NUM, ADDRESS, PHONE, PNAME, SALEPRICE, RESULT
  FROM ORDER_VIEW
where MNAME like '%김나리%' 
order by result, ONO DESC;

SELECT * FROM ORDERS;

SELECT * FROM ORDER_DETAIL WHERE ono = 1;

UPDATE ORDER_DETAIL 
   SET RESULT_YN = '2'
 WHERE ONO = 1;